{
 "title": "control computer",
 "time": { "from": "2022-03-17T19:02:13.000Z", "to": "2022-03-18T13:44:05.000Z" },
 "panels": [
  {
   "title": "control computer Maxrss",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT time, value, station from ts_param_cc_clientglobalMaxrss ORDER BY time ASC\n",
     "rawQueryText": "SELECT time, value, station from ts_param_cc_clientglobalMaxrss ORDER BY time ASC\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "control computer Stime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT time, value, station from ts_param_cc_clientglobalStime ORDER BY time ASC\n",
     "rawQueryText": "SELECT time, value, station from ts_param_cc_clientglobalStime ORDER BY time ASC\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "control computer Utime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "queryText": "SELECT time, value, station from ts_param_cc_clientglobalUtime ORDER BY time ASC\n",
     "rawQueryText": "SELECT time, value, station from ts_param_cc_clientglobalUtime ORDER BY time ASC\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}